import type { ScanResult } from "./types.js";

export type ProjectType = ScanResult["projectType"];

/**
 * The concrete commands a gate should run for a given project, resolved at
 * `helm init` time. `null` means "no sensible default" — the gate falls back
 * to its own in-script detection (or skips).
 */
export interface ProjectCommands {
  type: ProjectType;
  build: string | null;
  lint: string | null;
  test: string | null;
  coverage: string | null;
}

/**
 * Resolve gate commands from the detected project type. For Node projects the
 * project's own package.json scripts take precedence over guesses, so the
 * gates run what the project actually configured (DESIGN.md: "检测已有 scripts").
 */
export function resolveProjectCommands(
  type: ProjectType,
  pkgScripts?: Record<string, string>,
): ProjectCommands {
  switch (type) {
    case "node": {
      const has = (k: string) =>
        Boolean(pkgScripts && typeof pkgScripts[k] === "string" && pkgScripts[k].trim() !== "");
      return {
        type,
        build: has("build") ? "npm run build" : null,
        lint: has("lint") ? "npm run lint" : "npx eslint .",
        test: has("test") ? "npm test" : null,
        coverage: "npx c8 --reporter=text-summary npm test",
      };
    }
    case "python":
      return { type, build: null, lint: "ruff check .", test: "pytest", coverage: "pytest --cov" };
    case "rust":
      return { type, build: "cargo check", lint: "cargo clippy -- -D warnings", test: "cargo test", coverage: null };
    case "go":
      return { type, build: "go build ./...", lint: "go vet ./...", test: "go test ./...", coverage: "go test -cover ./..." };
    case "java":
      return { type, build: "mvn -q compile", lint: null, test: "mvn -q test", coverage: null };
    case "ruby":
      return { type, build: null, lint: "rubocop", test: "bundle exec rspec", coverage: null };
    default:
      return { type, build: null, lint: null, test: null, coverage: null };
  }
}

/**
 * Render ProjectCommands as a shell-sourceable env file. Null commands are
 * omitted so a gate's `${HELM_*_CMD:-}` check is empty and it falls back to
 * its own detection.
 */
export function renderProjectEnv(cmds: ProjectCommands): string {
  const lines = [
    "# Generated by `helm init` — concrete gate commands for this project.",
    "# Gates source this file; unset values fall back to in-script detection.",
    "# Edit to override, or delete and re-run `helm init` to regenerate.",
    `HELM_PROJECT_TYPE="${cmds.type}"`,
  ];
  const add = (key: string, val: string | null) => {
    if (val) lines.push(`${key}="${val}"`);
  };
  add("HELM_BUILD_CMD", cmds.build);
  add("HELM_LINT_CMD", cmds.lint);
  add("HELM_TEST_CMD", cmds.test);
  add("HELM_COVERAGE_CMD", cmds.coverage);
  return lines.join("\n") + "\n";
}
